import { Platform, StyleSheet } from 'react-native';
import { Colors } from './colors';
import { Spacing } from './spacing';
import { ERP_DOC_FLAT } from './erpDocFlatUi';

/** Shared flat palette + layout for share / forward recipient pickers. */
export const SHARE_PICKER_FLAT = ERP_DOC_FLAT;

export const sharePickerFlatStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: ERP_DOC_FLAT.pageBg },
  flex: { flex: 1 },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 6,
    paddingBottom: 10,
    paddingTop: 2,
    backgroundColor: ERP_DOC_FLAT.surface,
    borderBottomWidth: ERP_DOC_FLAT.hairline,
    borderBottomColor: ERP_DOC_FLAT.border,
  },
  backWrap: { padding: 8 },
  topTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '700',
    color: ERP_DOC_FLAT.ink,
    letterSpacing: -0.3,
  },
  topSubtitle: {
    textAlign: 'center',
    fontSize: 13,
    fontWeight: '500',
    color: ERP_DOC_FLAT.muted,
    marginTop: 2,
    paddingHorizontal: Spacing.MD,
    marginBottom: 8,
  },
  heroCard: {
    marginHorizontal: Spacing.MD,
    marginTop: Spacing.SM,
    marginBottom: Spacing.SM,
    paddingVertical: Spacing.SM,
    paddingHorizontal: Spacing.MD,
    backgroundColor: ERP_DOC_FLAT.surface,
    borderRadius: 12,
    borderWidth: ERP_DOC_FLAT.hairline,
    borderColor: ERP_DOC_FLAT.border,
  },
  heroRow: { flexDirection: 'row', alignItems: 'center' },
  heroIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: ERP_DOC_FLAT.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  heroEyebrow: {
    fontSize: 12,
    fontWeight: '600',
    color: ERP_DOC_FLAT.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  heroTitle: { fontSize: 16, fontWeight: '700', color: ERP_DOC_FLAT.ink, marginTop: 2 },
  heroHint: {
    fontSize: 13,
    color: ERP_DOC_FLAT.muted,
    lineHeight: 18,
    marginTop: 10,
  },
  searchWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: ERP_DOC_FLAT.surface,
    marginHorizontal: Spacing.MD,
    borderRadius: 10,
    borderWidth: ERP_DOC_FLAT.hairline,
    borderColor: ERP_DOC_FLAT.border,
    paddingHorizontal: 12,
    paddingVertical: Platform.OS === 'ios' ? 10 : 4,
    marginBottom: Spacing.SM,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: ERP_DOC_FLAT.ink,
    paddingVertical: Platform.OS === 'android' ? 8 : 0,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: ERP_DOC_FLAT.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginTop: Spacing.SM,
    marginBottom: 6,
    marginHorizontal: Spacing.MD,
  },
  contactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: Spacing.MD,
    backgroundColor: ERP_DOC_FLAT.surface,
    borderBottomWidth: ERP_DOC_FLAT.hairline,
    borderBottomColor: ERP_DOC_FLAT.border,
    minHeight: 68,
  },
  contactRowSelected: { backgroundColor: '#FDF2F4' },
  contactRowPressed: { opacity: 0.88 },
  contactAvatarSlot: {
    width: 56,
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  contactRowMain: {
    flex: 1,
    minWidth: 0,
    justifyContent: 'center',
    paddingRight: 8,
  },
  contactRowIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: ERP_DOC_FLAT.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  contactRowLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: ERP_DOC_FLAT.ink,
    lineHeight: 22,
  },
  documentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: Spacing.MD,
    marginBottom: 10,
    padding: 14,
    borderRadius: 10,
    backgroundColor: ERP_DOC_FLAT.surface,
    borderWidth: ERP_DOC_FLAT.hairline,
    borderColor: ERP_DOC_FLAT.border,
  },
  documentRowSelected: {
    borderColor: Colors.WINE,
    backgroundColor: '#FDF2F4',
  },
  documentRowDisabled: { opacity: 0.55 },
  documentRowMain: { flex: 1, minWidth: 0, marginRight: 8 },
  documentRowTitle: { fontSize: 15, fontWeight: '700', color: ERP_DOC_FLAT.ink },
  documentRowSub: { marginTop: 4, fontSize: 13, color: ERP_DOC_FLAT.muted, lineHeight: 18 },
  pickListFooter: {
    padding: Spacing.MD,
    borderTopWidth: ERP_DOC_FLAT.hairline,
    borderTopColor: ERP_DOC_FLAT.border,
    backgroundColor: ERP_DOC_FLAT.surface,
  },
  pickListContinueBtn: {
    backgroundColor: Colors.WINE,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pickListContinueBtnOff: { opacity: 0.5 },
  pickListContinueText: { color: Colors.WHITE, fontSize: 16, fontWeight: '700' },
  pickListHint: {
    textAlign: 'center',
    fontSize: 13,
    color: ERP_DOC_FLAT.muted,
    marginBottom: 10,
    paddingHorizontal: Spacing.MD,
  },
  linkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: Spacing.MD,
    marginHorizontal: Spacing.MD,
    marginBottom: Spacing.SM,
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: ERP_DOC_FLAT.surface,
    borderWidth: ERP_DOC_FLAT.hairline,
    borderColor: ERP_DOC_FLAT.border,
  },
  linkRowIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#FDF2F4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  linkRowText: { flex: 1, minWidth: 0 },
  linkRowTitle: { fontSize: 15, fontWeight: '700', color: ERP_DOC_FLAT.ink },
  linkRowSub: { marginTop: 3, fontSize: 13, color: ERP_DOC_FLAT.muted, lineHeight: 18 },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginHorizontal: Spacing.MD,
    marginBottom: Spacing.MD,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 10,
    backgroundColor: ERP_DOC_FLAT.surface,
    borderWidth: ERP_DOC_FLAT.hairline,
    borderColor: ERP_DOC_FLAT.border,
  },
  actionRowText: { fontSize: 15, fontWeight: '600', color: Colors.WINE },
  footer: {
    flexDirection: 'row',
    gap: 10,
    padding: Spacing.MD,
    borderTopWidth: ERP_DOC_FLAT.hairline,
    borderTopColor: ERP_DOC_FLAT.border,
    backgroundColor: ERP_DOC_FLAT.surface,
  },
  footerSecondaryBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: ERP_DOC_FLAT.hairline,
    borderColor: ERP_DOC_FLAT.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: ERP_DOC_FLAT.surface,
  },
  footerSecondaryText: { fontSize: 16, fontWeight: '700', color: ERP_DOC_FLAT.ink },
  footerPrimaryBtn: {
    backgroundColor: Colors.WINE,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerPrimaryBtnWide: { flex: 2 },
  footerPrimaryBtnFull: { flex: 1 },
  footerPrimaryBtnOff: { opacity: 0.55 },
  footerPrimaryText: { color: Colors.WHITE, fontSize: 16, fontWeight: '700' },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: Spacing.LG },
  emptyText: { textAlign: 'center', color: ERP_DOC_FLAT.muted, lineHeight: 20, fontSize: 14, padding: Spacing.LG },
  selectedCount: {
    paddingHorizontal: Spacing.MD,
    paddingBottom: 6,
    fontSize: 12,
    fontWeight: '700',
    color: ERP_DOC_FLAT.muted,
  },
  listContent: { paddingBottom: Spacing.MD },
  list: { flex: 1 },
  avatarRing: {
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'visible',
  },
  avatarRingSelected: {
    borderWidth: 2,
    borderColor: Colors.WINE,
  },
  recentBlock: { marginBottom: Spacing.SM },
  recentLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: ERP_DOC_FLAT.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 8,
    marginHorizontal: Spacing.MD,
  },
  recentRow: { paddingHorizontal: Spacing.MD, paddingBottom: 4, gap: 12 },
  recentItem: { width: 80, alignItems: 'center' },
  recentAvatarSlot: {
    width: 64,
    height: 64,
    alignItems: 'center',
    justifyContent: 'center',
  },
  recentName: {
    marginTop: 8,
    fontSize: 12,
    fontWeight: '600',
    color: ERP_DOC_FLAT.ink,
    textAlign: 'center',
    lineHeight: 16,
    width: '100%',
    paddingHorizontal: 2,
  },
  loadingWrap: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: Spacing.LG },
  loadingText: { marginTop: 10, color: ERP_DOC_FLAT.muted, fontSize: 14 },
  emptyWrap: { flex: 1, padding: Spacing.LG, justifyContent: 'center' },
  filterEmpty: {
    textAlign: 'center',
    color: ERP_DOC_FLAT.muted,
    paddingVertical: Spacing.LG,
    paddingHorizontal: Spacing.MD,
    fontSize: 14,
  },
  embeddedRoot: { flex: 1, backgroundColor: ERP_DOC_FLAT.pageBg },
});
